Cleaned up shell scripts andf installation procedures. Follow0up to Benjamins TG support removal.

diff --git a/bin/runJava b/bin/runJava
--- a/bin/runJava
+++ b/bin/runJava
@@ -20,18 +20,20 @@ resolve_symlink  ()
 UNAME=`uname -s 2>/dev/null | tr '[:upper:]' '[:lower:]'`
 ARCH=`uname -pm 2>/dev/null | tr '[:upper:]' '[:lower:]' | tr ' ' '-'`
 
-
 if [ -z "$JAVA_HOME" ] ; then
+    JAVA=`which java`
+    if [ -z "$JAVA" ] ; then
+	echo "Cannot find JAVA. Please set your PATH or \$JAVA_HOME."
+	exit 1
+    fi
+else
     if [ "$UNAME" = "darwin" ] ; then
-	JAVA_HOME="/System/Library/Frameworks/JavaVM.framework"
+	JRE=$JAVA_HOME/Home
+	JAVA=$JRE/bin/java
+# other OS
     else
-	JAVA=`which java`
-	if [ -z "$JAVA" ] ; then
-	    echo "Cannot find JAVA. Please set your PATH or \$JAVA_HOME."
-	    exit 1
-	fi
-	JAVA_BIN=`dirname $JAVA`
-	JAVA_HOME="$JAVA_BIN/.."
+	JRE=$JAVA_HOME/jre
+	JAVA=$JRE/bin/java
     fi
 fi
 echo "Using JDK installation from:      $JAVA_HOME"
@@ -41,89 +43,8 @@ echo "Using JDK installation from:      $JAVA_HOME"
 JAVA_OPTIONS=
 #JAVA_OPTIONS=-classic
 
-#JAVA_OPTIONS='-Xdebug -Xnoagent -Djava.compiler=NONE -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=1234'
-
-# Change that, if your java interpreter is different
-#
-# MAC OS X
-if [ "$UNAME" = "darwin" ] ; then
-    JRE=$JAVA_HOME/Home
-    JDK_RT_JAR=$JAVA_HOME/Classes/classes.jar
-    JDK_UI_JAR=$JAVA_HOME/Classes/ui.jar
-    # we do not need it in macosX
-    # JDK_TOOLS_JAR=$JAVA_HOME/Home/lib/ext/jpda.jar
-    JAVA=$JRE/bin/java
-# other OS
-else
-    JRE=$JAVA_HOME/jre
-    JDK_RT_JAR=$JRE/lib/rt.jar
-    JDK_TOOLS_JAR=$JAVA_HOME/lib/tools.jar
-    JAVA=$JRE/bin/java
-fi
-
-
-#LD_LIBRARY_PATH=$JAVA_HOME/lib/i386:$LD_LIBRARY_PATH
-#export LD_LIBRARY_PATH
-
-if [ "D""$JAVA_HOME" = "D" ]
-then
-    echo
-    echo Please provide a valid path to the recommended JDK by
-    echo either configuring the file "$0" or defining the
-    echo JAVA_HOME environment variable from the command line.
-    echo
-    echo If you have any problems or questions, please contact
-    echo "technical support (http://www.togethersoft.com/support/)"
-    exit
-else
-    if [ ! -x $JAVA ] ; then
-        echo Please be sure you have properly set the JAVA_HOME variable.
-        echo The executable file $JAVA is not found.
-        exit
-    fi
-
-    if [ ! -r $JDK_RT_JAR ] ; then
-        echo Please be sure you have properly set the JDK_RT_JAR variable.
-        echo The file $JDK_RT_JAR is not found.
-        echo
-        echo If you have any problems or questions, please contact
-        echo "technical support (http://www.togethersoft.com/support/)"
-        exit
-    fi
-
-    # we do not need this in MacOS X
-    if [ "$UNAME" != "darwin" ] ; then
-	if [ ! -r $JDK_TOOLS_JAR ] ; then
-            echo The file $JDK_TOOLS_JAR was not found. This is probably
-            echo because you are using a JRE instead of a JDK. You will
-            echo not be able to run javac or javadoc. This is probably OK.
-	fi
-    fi
-
-    if [ "$UNAME" = "darwin" ] ; then
-        if [ ! -r $JDK_UI_JAR ] ; then
-            echo Please be sure you have properly installed JDK 1.3.
-            echo The file $JDK_UI_JAR is not found.  
-            echo
-            echo If you have any problems or questions, please contact
-            echo "technical support (http://www.togethersoft.com/support/)"
-            exit
-        fi
-        JDK_RT_JAR=$JDK_RT_JAR:$JDK_UI_JAR 
-    fi
-fi
-
-
-# fixing of possible linux glibc bug for jdk 1.3.1
-# http://developer.java.sun.com/developer/bugParade/bugs/4466587.html
-if [ "$UNAME" = "linux" ] ; then
-    VERSION=`$JAVA $JAVA_OPTIONS -version 2>&1 | awk 'BEGIN {FS="\""}\
-    { for(i = 2; i<NF; i++) printf "%s", \$i }'`
-    if expr "$VERSION" : "1\\.3\\.1.*" > /dev/null 2>&1; then
-       ulimit -s 2048
-    fi
-fi
-
+# Uncomment the following definition for remote debugging on port 1234
+#JAVA_OPTIONS='-DKeyDebugFlag=on -Xdebug -Xnoagent -Djava.compiler=NONE -Xrunjdwp:transport=dt_socket,server=y,suspend=y,address=1234'
 
 #
 # Now $KEY_HOME  
@@ -145,52 +66,11 @@ echo "Using libraries from:             $KEY_LIB"
 fi
 
 
-##################### TOGETHER HOME ########################
-
-
-
-
-if [ -z "$TOGETHER_HOME"  ]
-then
-   if [ -d "$KEY_LIB/TOGETHER" ] ; then
-      TOGETHER_HOME=`resolve_symlink "$KEY_LIB/TOGETHER"`
-   else
-      echo
-      echo Please set the \$TOGETHER_HOME environment variable.
-      echo
-      echo If you have any problems or questions, please contact
-      echo "technical support (http://www.togethersoft.com/support/)"
-      exit
-   fi
-
-fi
-TGH="$TOGETHER_HOME"
-echo "Using Together installation from: $TGH"
-
-
-
-PATH=$TGH/bin/$UNAME/$ARCH:$TGH/bin/unix:$JAVA_HOME:$JAVA_HOME/bin:$JAVA_HOME/lib:$PATH
-export PATH
-
-if expr "`uname -s`" : "HP-UX" > /dev/null 2>&1; then
- hpfix="-Dhpux.im.disable=true"
-fi
-
-if [ -r "$TGH/lib/jndi.jar" ]; then
-    JNDI=$TGH/lib/jndi.jar:
-else
-    JNDI=""
-fi
-
-JVM_DIR=`expr $JAVA : '\(.*\)/.*' \| $JAVA`
-
-
 #
 # KeY CLASSPATH
 #
 
-key_ext_jars="antlr.jar recoderKey.jar dresden-ocl-demo.jar xerces.jar \
-junit.jar log4j.jar jargs.jar"
+key_ext_jars="antlr.jar jargs.jar recoderKey.jar log4j.jar"
 
 keyclasspath="$KEY_HOME/system/binary/"
 
@@ -213,13 +93,35 @@ then
   keyclasspath=$keyclasspath:$ASPECTJRTPATH
 fi
 
-## jcoverage (stuff; optional)
-keyclasspath="$KEY_HOME/system/instrumented/:${keyclasspath}:$KEY_LIB/jcoverage.jar"
-
-
 #
-# User specific Together configuration
+# KeY-specific command line options
 #
+
+keysysprops=""
+while [ $# -ne 0 ]; do
+    case $1 in
+        -keydebug) keysysprops="${keysysprops}-DKeyDebugFlag=on "
+            shift
+            continue;;
+
+        -server) keysysprops="${keysysprops}-server "
+            shift
+            continue;;
+
+        -debugclassloader) keysysprops="${keysysprops}-DKeyDebugClassLoader=on "
+            shift
+            continue;;
+
+        -*)  keysysprops="${keysysprops}${1} "
+            shift
+            continue;;
+
+        *)  keyarg="${keyarg}${1} "
+            shift
+            continue;;
+    esac
+done	
+
 
 if [ ! -d "$HOME/.key" ]
 then
@@ -227,38 +129,13 @@ mkdir "$HOME/.key"
 fi
 
 
+# Fallback for KeY-specific binaries
+PATH=${PATH}:$KEY_LIB
+export PATH
+
 #
 # This command actually runs KeY
 # 
-$JAVA $JAVA_OPTIONS $keysysprops  $hpfix \
--noverify -Djvm.dir=$JVM_DIR -Xms64m -Xmx512m \
+$JAVA $JAVA_OPTIONS $keysysprops -Xms64m -Xmx512m \
 -Dkey.home=$KEY_HOME \
--Dkey.pattern.path=$HOME/.key/keypatterns/ \
--classpath $keyclasspath:\
-$TGH/lib/together.jar:\
-$TGH/lib/tgscilib.jar:\
-$TGH/lib/openapi.jar:\
-$TGH/modules:\
-$TGH/lib/gifs.zip:\
-$TGH/out/classes:\
-$TGH/lib/i18n:\
-$TGH/lib/jgl.zip:\
-$TGH/lib/jacl.jar:\
-$TGH/lib/uddi4j.jar:\
-$TGH/lib/mail.jar:\
-$TGH/lib/xalan.jar:\
-$TGH/lib/xerces.jar:\
-$JNDI\
-$TGH/lib/tcljava.jar:\
-$TGH/lib/jcvs/jars/jcvsii.jar:\
-$TGH/lib/jcpagelayout.jar:\
-$TGH/lib/misclib.zip:\
-$TGH/lib/javax.jar:\
-$JDK_TOOLS_JAR:\
-$TGH/lib/jhall.jar:\
-$TGH/help/together-help.jar:\
-$TGH/bundled/tomcat/lib/servlet.jar:\
-$TGH/lib/soap.jar:\
-$TGH/bundled/j2ee/lib/j2ee.jar:\
-$TGH/lib/guiBuilderBeanInfo.jar:\
-$JDK_RT_JAR $1 $2 $3 $4
+-classpath $keyclasspath $1 $2 $3 $4
diff --git a/bin/runKeYDoc b/bin/runKeYDoc
--- a/bin/runKeYDoc
+++ b/bin/runKeYDoc
@@ -20,117 +20,27 @@ resolve_symlink  ()
 UNAME=`uname -s 2>/dev/null | tr '[:upper:]' '[:lower:]'`
 ARCH=`uname -pm 2>/dev/null | tr '[:upper:]' '[:lower:]' | tr ' ' '-'`
 
-
 if [ -z "$JAVA_HOME" ] ; then
+    JAVA=`which java`
+    if [ -z "$JAVA" ] ; then
+	echo "Cannot find JAVA. Please set your PATH or \$JAVA_HOME."
+	exit 1
+    fi
+else
     if [ "$UNAME" = "darwin" ] ; then
-	JAVA_HOME="/System/Library/Frameworks/JavaVM.framework"
+	JRE=$JAVA_HOME/Home
+	JAVA=$JRE/bin/java
+# other OS
     else
-	JAVA=`which java`
-	if [ -z "$JAVA" ] ; then
-	    echo "Cannot find JAVA. Please set your PATH or \$JAVA_HOME."
-	    exit 1
-	fi
-	JAVA_BIN=`dirname $JAVA`
-	JAVA_HOME="$JAVA_BIN/.."
+	JRE=$JAVA_HOME/jre
+	JAVA=$JRE/bin/java
     fi
 fi
 echo "Using JDK installation from:      $JAVA_HOME"
 
 
 # For debugging reasons disable JIT (otherwise strace doesn't work)
-#JAVA_OPTIONS="-Djava.library.path=/home/vladimir/lib -Xrunjprofiler:port=8887 -Xbootclasspath/a:/home/vladimir/jprofiler3/bin/agent.jar"
 JAVA_OPTIONS=
-#JAVA_OPTIONS=-classic
-
-# Uncomment the following definition for remote debugging on port 1234
-#JAVA_OPTIONS='-Xdebug -Xnoagent -Djava.compiler=NONE -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=1234'
-
-# Uncomment the following definition for profiling
-#JAVA_OPTIONS=-Xrunhprof:cpu=samples,format=a,thread=y,file=log.txt,depth=20
-#JAVA_OPTIONS="-Djava.library.path=/home/vladimir/lib -Xrunjprofiler:port=8887 -Xbootclasspath/a:/home/vladimir/jprofiler3/bin/agent.jar"
-#JAVA_OPTIONS="-Xint -Xrunjprofiler:port=8849  -Xbootclasspath/a:/usr/local/java/jprofiler3/bin/agent.jar"
-
-
-# Change that, if your java interpreter is different
-#
-# MAC OS X
-if [ "$UNAME" = "darwin" ] ; then
-    JRE=$JAVA_HOME/Home
-    JDK_RT_JAR=$JAVA_HOME/Classes/classes.jar
-    JDK_UI_JAR=$JAVA_HOME/Classes/ui.jar
-    # we do not need it in macosX
-    #JDK_TOOLS_JAR=$JAVA_HOME/Home/lib/ext/jpda.jar
-    JAVA=$JRE/bin/java
-# other OS
-else
-    JRE=$JAVA_HOME/jre
-    JDK_RT_JAR=$JRE/lib/rt.jar
-    JDK_TOOLS_JAR=$JAVA_HOME/lib/tools.jar
-    JAVA=$JRE/bin/java
-fi
-
-#LD_LIBRARY_PATH=$JAVA_HOME/lib/i386:$LD_LIBRARY_PATH
-#export LD_LIBRARY_PATH
-
-if [ "D""$JAVA_HOME" = "D" ]
-then
-    echo
-    echo Please provide a valid path to the recommended JDK by
-    echo either configuring the file "$0" or defining the
-    echo JAVA_HOME environment variable from the command line.
-    echo
-    echo If you have any problems or questions, please contact
-    echo "technical support (http://www.togethersoft.com/support/)"
-    exit
-else
-    if [ ! -x $JAVA ] ; then
-        echo Please be sure you have properly set the JAVA_HOME variable.
-        echo The executable file $JAVA is not found.
-        exit
-    fi
-
-    if [ ! -r $JDK_RT_JAR ] ; then
-        echo Please be sure you have properly set the JDK_RT_JAR variable.
-        echo The file $JDK_RT_JAR is not found.
-        echo
-        echo If you have any problems or questions, please contact
-        echo "technical support (http://www.togethersoft.com/support/)"
-        exit
-    fi
-
-    # we do not need this in MacOS X
-    if [ "$UNAME" != "darwin" ] ; then
-	if [ ! -r $JDK_TOOLS_JAR ] ; then
-            echo The file $JDK_TOOLS_JAR was not found. This is probably
-            echo because you are using a JRE instead of a JDK. You will
-            echo not be able to run javac or javadoc. This is probably OK.
-	fi
-    fi
-
-    if [ "$UNAME" = "darwin" ] ; then
-        if [ ! -r $JDK_UI_JAR ] ; then
-            echo Please be sure you have properly installed JDK 1.3.
-            echo The file $JDK_UI_JAR is not found.  
-            echo
-            echo If you have any problems or questions, please contact
-            echo "technical support (http://www.togethersoft.com/support/)"
-            exit
-        fi
-        JDK_RT_JAR=$JDK_RT_JAR:$JDK_UI_JAR 
-    fi
-fi
-
-
-# fixing of possible linux glibc bug for jdk 1.3.1
-# http://developer.java.sun.com/developer/bugParade/bugs/4466587.html
-if [ "$UNAME" = "linux" ] ; then
-    VERSION=`$JAVA -version 2>&1 | awk 'BEGIN {FS="\""}\
-    { for(i = 2; i<NF; i++) printf "%s", \$i }'`
-    if expr "$VERSION" : "1\\.3\\.1.*" > /dev/null 2>&1; then
-       ulimit -s 2048
-    fi
-fi
-
 
 #
 # Now $KEY_HOME  
@@ -156,7 +66,7 @@ fi
 # KeY CLASSPATH
 #
 
-key_ext_jars="antlr.jar jargs.jar recoderKey.jar dresden-ocl-demo.jar xerces.jar log4j.jar"
+key_ext_jars="antlr.jar jargs.jar recoderKey.jar log4j.jar"
 
 keyclasspath="$KEY_HOME/system/binary/"
 
@@ -179,21 +89,43 @@ then
   keyclasspath=$keyclasspath:$ASPECTJRTPATH
 fi
 
+#
+# KeY-specific command line options
+#
 
-#
-# User specific Together configuration
-#
+keysysprops=""
+while [ $# -ne 0 ]; do
+    case $1 in
+        -keydebug) keysysprops="${keysysprops}-DKeyDebugFlag=on "
+            shift
+            continue;;
+
+        -server) keysysprops="${keysysprops}-server "
+            shift
+            continue;;
+
+        -debugclassloader) keysysprops="${keysysprops}-DKeyDebugClassLoader=on "
+            shift
+            continue;;
+
+        -*)  keysysprops="${keysysprops}${1} "
+            shift
+            continue;;
+
+        *)  keyarg="${keyarg}${1} "
+            shift
+            continue;;
+    esac
+done	
 
 if [ ! -d "$HOME/.key" ]
 then
 mkdir "$HOME/.key"
 fi
 
-
 # Fallback for KeY-specific binaries
 PATH=${PATH}:$KEY_LIB
 export PATH
-
 
 #
 # This command actually runs KeY
@@ -201,8 +133,8 @@ export PATH
 #-server \
 #-XX:CompileThreshold=1500 \
 
-$JAVA $JAVA_OPTIONS $keysysprops $hpfix \
--ea:de.uka.ilkd.key... -noverify -Djvm.dir=$JVM_DIR -Xms64m -Xmx512m \
+$JAVA $JAVA_OPTIONS $keysysprops \
+-ea:de.uka.ilkd.key... -Xms64m -Xmx512m \
 -Dkey.home=$KEY_HOME \
--classpath $keyclasspath:$togetherclasspath:$JDK_RT_JAR de.uka.ilkd.key.util.keydoc.html.KeYDoc $@
+-classpath $keyclasspath de.uka.ilkd.key.util.keydoc.html.KeYDoc $@
 
