Correct parsing of command line arguments in runAllProofs shell script.

diff --git a/key/scripts/runAllProofs b/key/scripts/runAllProofs
--- a/key/scripts/runAllProofs
+++ b/key/scripts/runAllProofs
@@ -1,4 +1,4 @@
-#!/bin/sh
+#!/bin/bash
 
 resolve_symlink  ()
 {
@@ -17,6 +17,60 @@ resolve_symlink  ()
    echo "$RESULT"
 }
 
+list_help(){
+    echo "Usage: runAllProofs [--forkMode=<perFile|perGroup|noFork>] <groupNames>"
+    echo "Example: runAllProofs --forkMode=perFile newBook comprehensions"
+}
+
+#
+# Parse command line arguments
+#
+
+case $1 in
+    --forkMode=*)
+    FORKMODE=$(echo $1 | cut -d'=' -f 2)
+    shift
+    ;;
+    -h|--help|-?)
+    list_help
+    exit
+    ;;
+esac
+
+if [ $# > 0 ]
+then
+
+TESTCASES=$1
+shift
+
+while [[ $# > 0 ]]
+do
+TESTCASES="$TESTCASES $1"
+shift
+done
+fi
+
+UNAME=`uname -s 2>/dev/null | tr '[:upper:]' '[:lower:]'`
+ARCH=`uname -pm 2>/dev/null | tr '[:upper:]' '[:lower:]' | tr ' ' '-'`
+
+if [ -z "$JAVA_HOME" ] ; then
+    JAVA=`which java`
+    if [ -z "$JAVA" ] ; then
+	echo "Cannot find JAVA. Please set your PATH or \$JAVA_HOME."
+	exit 1
+    fi
+else
+    echo "Using JDK installation from:      $JAVA_HOME"
+    if [ "$UNAME" = "darwin" ] ; then
+	JRE=$JAVA_HOME/Home
+	JAVA=$JRE/bin/java
+# other OS
+    else
+	JRE=$JAVA_HOME/jre
+	JAVA=$JRE/bin/java
+    fi
+fi
+
 #
 # Determining $KEY_HOME environment variable.
 #
@@ -29,4 +83,53 @@ if [ -z "$KEY_HOME" ] ; then
 fi
 echo "Using KeY installation from:      $KEY_HOME"
 
-ant -f $KEY_HOME/key.core.test/build.xml runAllProofs #-Dkey.runallproofs.*=?
+
+KEY_LIB="$KEY_HOME/key.core/lib"
+
+
+#
+# KeY CLASSPATH
+#
+
+key_ext_jars="antlr.jar recoderKey.jar"
+
+keyclasspath="$KEY_HOME/key.core/bin:$KEY_HOME/key.ui/bin:$KEY_HOME/key.util/bin:$KEY_HOME/key.core.proof_reference/bin:$KEY_HOME/key.core.symbolic_execution/bin:$KEY_HOME/key.core.testgen/bin:$KEY_HOME/key.core.test/bin"
+
+
+for i in $key_ext_jars ; do
+    current_jar="$KEY_LIB/$i"
+    if [ ! -f "$current_jar" ]
+    then
+       echo Cannot find $current_jar.
+       echo Copy or link the file into the
+       echo $KEY_LIB directory.
+       exit 1
+    else
+       keyclasspath="${keyclasspath}:$current_jar"
+    fi
+done
+
+KEY_LIB_JUNIT="$KEY_HOME/key.util.test/lib"
+
+key_junit_jars="hamcrest-core-1.3.jar  junit-4.12.jar"
+
+for i in $key_junit_jars ; do
+    current_jar="$KEY_LIB_JUNIT/$i"
+    if [ ! -f "$current_jar" ]
+    then
+       echo Cannot find $current_jar.
+       echo Copy or link the file into the
+       echo $KEY_LIB_JUNIT directory.
+       exit 1
+    else
+       keyclasspath="${keyclasspath}:$current_jar"
+    fi
+done
+
+$JAVA $keysysprops \
+-ea:de.uka.ilkd.key... -noverify -Djvm.dir=$JVM_DIR -Xms64m -Xmx2048m \
+-Dkey.home="$KEY_HOME" \
+-Djava.awt.headless=true \
+-Dkey.runallproofs.forkmode=$FORKMODE \
+-Dkey.runallproofs.testcases="$TESTCASES" \
+-classpath "$keyclasspath" org.junit.runner.JUnitCore de.uka.ilkd.key.proof.runallproofs.RunAllProofsTest
